import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Clearing existing database records...');
  await prisma.application.deleteMany();
  await prisma.emiPlan.deleteMany();
  await prisma.productVariant.deleteMany();
  await prisma.product.deleteMany();

  console.log('Seeding products, variants, and mutual fund-backed EMI plans...');

  // 1. iPhone 17 Pro
  const iphone17 = await prisma.product.create({
    data: {
      slug: 'iphone-17-pro',
      title: 'iPhone 17 Pro',
      brand: 'Apple',
      category: 'Smartphones',
      badge: 'NEW',
      rating: 4.9,
      reviewCount: 1842,
      description: 'The ultimate iPhone engineered with an aerospace-grade titanium design, revolutionary A19 Pro Bionic silicon, next-generation 48MP triple telephoto camera system with 5x optical zoom, and ultra-durable Ceramic Shield 2. Available with zero down-payment on 1Fi Mutual Fund-backed EMI plans.',
      features: JSON.stringify([
        { title: 'Chipset', value: 'Apple A19 Pro (3nm Gen 2)' },
        { title: 'Display', value: '6.3" Super Retina XDR OLED, 120Hz ProMotion, 2500 nits' },
        { title: 'Camera', value: '48MP Main + 48MP Ultra-Wide + 48MP 5x Periscope Telephoto' },
        { title: 'Battery', value: 'Up to 29 hours video playback with MagSafe 25W Fast Charge' },
        { title: 'Build', value: 'Grade 5 Titanium frame with Matte textured glass back' },
        { title: 'Connectivity', value: '5G Sub-6/mmWave, Wi-Fi 7, Bluetooth 5.4, USB-C 3.2 (10Gbps)' },
      ]),
      variants: {
        create: [
          {
            name: 'Desert Titanium 256GB',
            colorName: 'Desert Titanium',
            colorHex: '#C5A089',
            storage: '256GB',
            mrp: 134900,
            price: 127400,
            stock: 28,
            imageUrl: '/images/iphone-17-pro-desert.png',
            galleryImages: JSON.stringify([
              '/images/iphone-17-pro-desert.png',
              '/images/iphone-17-pro-desert-back.png',
              '/images/iphone-17-pro-angle.png'
            ]),
            isDefault: true,
          },
          {
            name: 'Desert Titanium 512GB',
            colorName: 'Desert Titanium',
            colorHex: '#C5A089',
            storage: '512GB',
            mrp: 154900,
            price: 147400,
            stock: 15,
            imageUrl: '/images/iphone-17-pro-desert.png',
            galleryImages: JSON.stringify(['/images/iphone-17-pro-desert.png']),
            isDefault: false,
          },
          {
            name: 'Desert Titanium 1TB',
            colorName: 'Desert Titanium',
            colorHex: '#C5A089',
            storage: '1TB',
            mrp: 174900,
            price: 167400,
            stock: 8,
            imageUrl: '/images/iphone-17-pro-desert.png',
            galleryImages: JSON.stringify(['/images/iphone-17-pro-desert.png']),
            isDefault: false,
          },
          {
            name: 'Natural Titanium 256GB',
            colorName: 'Natural Titanium',
            colorHex: '#9E978E',
            storage: '256GB',
            mrp: 134900,
            price: 127400,
            stock: 22,
            imageUrl: '/images/iphone-17-pro-natural.png',
            galleryImages: JSON.stringify(['/images/iphone-17-pro-natural.png']),
            isDefault: false,
          },
          {
            name: 'Natural Titanium 512GB',
            colorName: 'Natural Titanium',
            colorHex: '#9E978E',
            storage: '512GB',
            mrp: 154900,
            price: 147400,
            stock: 12,
            imageUrl: '/images/iphone-17-pro-natural.png',
            galleryImages: JSON.stringify(['/images/iphone-17-pro-natural.png']),
            isDefault: false,
          },
          {
            name: 'Black Titanium 256GB',
            colorName: 'Black Titanium',
            colorHex: '#3C3B3A',
            storage: '256GB',
            mrp: 134900,
            price: 127400,
            stock: 30,
            imageUrl: '/images/iphone-17-pro-black.png',
            galleryImages: JSON.stringify(['/images/iphone-17-pro-black.png']),
            isDefault: false,
          },
          {
            name: 'White Titanium 256GB',
            colorName: 'White Titanium',
            colorHex: '#E3E4E5',
            storage: '256GB',
            mrp: 134900,
            price: 127400,
            stock: 19,
            imageUrl: '/images/iphone-17-pro-white.png',
            galleryImages: JSON.stringify(['/images/iphone-17-pro-white.png']),
            isDefault: false,
          },
        ],
      },
      emiPlans: {
        create: [
          {
            tenureMonths: 3,
            interestRate: 0.0,
            monthlyEmi: 44967,
            cashbackAmount: 7500,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 50000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 1,
          },
          {
            tenureMonths: 6,
            interestRate: 0.0,
            monthlyEmi: 22483,
            cashbackAmount: 7500,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 50000,
            expectedMfReturnsRate: 12.0,
            isPopular: true,
            orderIndex: 2,
          },
          {
            tenureMonths: 12,
            interestRate: 0.0,
            monthlyEmi: 11242,
            cashbackAmount: 7500,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 60000,
            expectedMfReturnsRate: 12.0,
            isPopular: true,
            orderIndex: 3,
          },
          {
            tenureMonths: 24,
            interestRate: 0.0,
            monthlyEmi: 5621,
            cashbackAmount: 7500,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 75000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 4,
          },
          {
            tenureMonths: 36,
            interestRate: 10.5,
            monthlyEmi: 4297,
            cashbackAmount: 7500,
            isZeroPercent: false,
            badgeText: '10.5% interest',
            minMfHolding: 80000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 5,
          },
          {
            tenureMonths: 48,
            interestRate: 10.5,
            monthlyEmi: 3385,
            cashbackAmount: 7500,
            isZeroPercent: false,
            badgeText: '10.5% interest',
            minMfHolding: 90000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 6,
          },
          {
            tenureMonths: 60,
            interestRate: 10.5,
            monthlyEmi: 2842,
            cashbackAmount: 7500,
            isZeroPercent: false,
            badgeText: '10.5% interest',
            minMfHolding: 100000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 7,
          },
        ],
      },
    },
  });

  // 2. Samsung Galaxy S24 Ultra
  const samsungS24 = await prisma.product.create({
    data: {
      slug: 'samsung-s24-ultra',
      title: 'Samsung Galaxy S24 Ultra',
      brand: 'Samsung',
      category: 'Smartphones',
      badge: 'GALAXY AI',
      rating: 4.8,
      reviewCount: 2310,
      description: 'Meet Galaxy S24 Ultra with Galaxy AI, titanium exterior armor, integrated S-Pen stylus, Snapdragon 8 Gen 3 for Galaxy, and an industry-leading 200MP Quad Telephoto camera with ProVisual engine.',
      features: JSON.stringify([
        { title: 'Chipset', value: 'Qualcomm Snapdragon 8 Gen 3 for Galaxy (4nm)' },
        { title: 'Display', value: '6.8" Dynamic AMOLED 2X, QHD+, 1-120Hz, Corning Gorilla Armor (2600 nits)' },
        { title: 'Camera', value: '200MP Wide + 50MP 5x Telephoto + 10MP 3x Telephoto + 12MP Ultra-Wide' },
        { title: 'Battery', value: '5000 mAh with 45W Fast Charging & Wireless PowerShare' },
        { title: 'Stylus', value: 'Built-in S Pen with Air Actions and 2.8ms ultra-low latency' },
        { title: 'AI Engine', value: 'Live Translate, Circle to Search with Google, Note Assist' },
      ]),
      variants: {
        create: [
          {
            name: 'Titanium Gray 256GB',
            colorName: 'Titanium Gray',
            colorHex: '#717378',
            storage: '256GB',
            mrp: 134999,
            price: 119999,
            stock: 35,
            imageUrl: '/images/samsung-s24-ultra-gray.png',
            galleryImages: JSON.stringify(['/images/samsung-s24-ultra-gray.png']),
            isDefault: true,
          },
          {
            name: 'Titanium Violet 256GB',
            colorName: 'Titanium Violet',
            colorHex: '#4C4556',
            storage: '256GB',
            mrp: 134999,
            price: 119999,
            stock: 18,
            imageUrl: '/images/samsung-s24-ultra-violet.png',
            galleryImages: JSON.stringify(['/images/samsung-s24-ultra-violet.png']),
            isDefault: false,
          },
          {
            name: 'Titanium Black 512GB',
            colorName: 'Titanium Black',
            colorHex: '#2B2B2C',
            storage: '512GB',
            mrp: 144999,
            price: 129999,
            stock: 14,
            imageUrl: '/images/samsung-s24-ultra-black.png',
            galleryImages: JSON.stringify(['/images/samsung-s24-ultra-black.png']),
            isDefault: false,
          },
          {
            name: 'Titanium Yellow 256GB',
            colorName: 'Titanium Yellow',
            colorHex: '#D5C8A6',
            storage: '256GB',
            mrp: 134999,
            price: 119999,
            stock: 10,
            imageUrl: '/images/samsung-s24-ultra-yellow.png',
            galleryImages: JSON.stringify(['/images/samsung-s24-ultra-yellow.png']),
            isDefault: false,
          },
        ],
      },
      emiPlans: {
        create: [
          {
            tenureMonths: 3,
            interestRate: 0.0,
            monthlyEmi: 42333,
            cashbackAmount: 7000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 45000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 1,
          },
          {
            tenureMonths: 6,
            interestRate: 0.0,
            monthlyEmi: 21166,
            cashbackAmount: 7000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 45000,
            expectedMfReturnsRate: 12.0,
            isPopular: true,
            orderIndex: 2,
          },
          {
            tenureMonths: 12,
            interestRate: 0.0,
            monthlyEmi: 10583,
            cashbackAmount: 7000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 55000,
            expectedMfReturnsRate: 12.0,
            isPopular: true,
            orderIndex: 3,
          },
          {
            tenureMonths: 24,
            interestRate: 0.0,
            monthlyEmi: 5291,
            cashbackAmount: 7000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 70000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 4,
          },
          {
            tenureMonths: 36,
            interestRate: 10.5,
            monthlyEmi: 4047,
            cashbackAmount: 7000,
            isZeroPercent: false,
            badgeText: '10.5% interest',
            minMfHolding: 75000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 5,
          },
          {
            tenureMonths: 48,
            interestRate: 10.5,
            monthlyEmi: 3188,
            cashbackAmount: 7000,
            isZeroPercent: false,
            badgeText: '10.5% interest',
            minMfHolding: 85000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 6,
          },
          {
            tenureMonths: 60,
            interestRate: 10.5,
            monthlyEmi: 2677,
            cashbackAmount: 7000,
            isZeroPercent: false,
            badgeText: '10.5% interest',
            minMfHolding: 95000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 7,
          },
        ],
      },
    },
  });

  // 3. Google Pixel 9 Pro
  const pixel9 = await prisma.product.create({
    data: {
      slug: 'google-pixel-9-pro',
      title: 'Google Pixel 9 Pro',
      brand: 'Google',
      category: 'Smartphones',
      badge: 'GEMINI AI',
      rating: 4.7,
      reviewCount: 940,
      description: 'Google Pixel 9 Pro features Google Tensor G4 with 16 GB of RAM, super actua display, Gemini Advanced on-device AI assistant, and a pro-level triple camera with 30x Super Res Zoom.',
      features: JSON.stringify([
        { title: 'Chipset', value: 'Google Tensor G4 with Titan M2 security coprocessor' },
        { title: 'Display', value: '6.3" Super Actua LTPO OLED, 1-120Hz, 3000 nits peak' },
        { title: 'Camera', value: '50MP Octa PD + 48MP Quad PD Telephoto (5x optical) + 48MP Ultra-Wide' },
        { title: 'Battery', value: '4700 mAh with 24+ hour battery life and Extreme Battery Saver' },
        { title: 'Memory', value: '16 GB RAM for on-device Gemini Nano multimodal intelligence' },
        { title: 'OS & Updates', value: '7 years of guaranteed OS, Security, and Pixel Feature Drops' },
      ]),
      variants: {
        create: [
          {
            name: 'Porcelain 128GB',
            colorName: 'Porcelain',
            colorHex: '#F0ECE1',
            storage: '128GB',
            mrp: 109999,
            price: 99999,
            stock: 20,
            imageUrl: '/images/google-pixel-9-pro-porcelain.png',
            galleryImages: JSON.stringify(['/images/google-pixel-9-pro-porcelain.png']),
            isDefault: true,
          },
          {
            name: 'Obsidian 256GB',
            colorName: 'Obsidian',
            colorHex: '#2D3033',
            storage: '256GB',
            mrp: 119999,
            price: 109999,
            stock: 16,
            imageUrl: '/images/google-pixel-9-pro-obsidian.png',
            galleryImages: JSON.stringify(['/images/google-pixel-9-pro-obsidian.png']),
            isDefault: false,
          },
          {
            name: 'Hazel 128GB',
            colorName: 'Hazel',
            colorHex: '#7C817A',
            storage: '128GB',
            mrp: 109999,
            price: 99999,
            stock: 12,
            imageUrl: '/images/google-pixel-9-pro-hazel.png',
            galleryImages: JSON.stringify(['/images/google-pixel-9-pro-hazel.png']),
            isDefault: false,
          },
          {
            name: 'Rose Quartz 256GB',
            colorName: 'Rose Quartz',
            colorHex: '#E5BAC2',
            storage: '256GB',
            mrp: 119999,
            price: 109999,
            stock: 9,
            imageUrl: '/images/google-pixel-9-pro-rose.png',
            galleryImages: JSON.stringify(['/images/google-pixel-9-pro-rose.png']),
            isDefault: false,
          },
        ],
      },
      emiPlans: {
        create: [
          {
            tenureMonths: 3,
            interestRate: 0.0,
            monthlyEmi: 35333,
            cashbackAmount: 6000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 40000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 1,
          },
          {
            tenureMonths: 6,
            interestRate: 0.0,
            monthlyEmi: 17666,
            cashbackAmount: 6000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 40000,
            expectedMfReturnsRate: 12.0,
            isPopular: true,
            orderIndex: 2,
          },
          {
            tenureMonths: 12,
            interestRate: 0.0,
            monthlyEmi: 8833,
            cashbackAmount: 6000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 50000,
            expectedMfReturnsRate: 12.0,
            isPopular: true,
            orderIndex: 3,
          },
          {
            tenureMonths: 24,
            interestRate: 0.0,
            monthlyEmi: 4416,
            cashbackAmount: 6000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 60000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 4,
          },
          {
            tenureMonths: 36,
            interestRate: 10.5,
            monthlyEmi: 3373,
            cashbackAmount: 6000,
            isZeroPercent: false,
            badgeText: '10.5% interest',
            minMfHolding: 70000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 5,
          },
          {
            tenureMonths: 48,
            interestRate: 10.5,
            monthlyEmi: 2657,
            cashbackAmount: 6000,
            isZeroPercent: false,
            badgeText: '10.5% interest',
            minMfHolding: 80000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 6,
          },
        ],
      },
    },
  });

  // 4. OnePlus 12
  const oneplus12 = await prisma.product.create({
    data: {
      slug: 'oneplus-12',
      title: 'OnePlus 12 5G',
      brand: 'OnePlus',
      category: 'Smartphones',
      badge: 'HASSELBLAD',
      rating: 4.8,
      reviewCount: 1560,
      description: 'OnePlus 12 delivers flagship-conquering performance powered by Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera for Mobile, vibrant 2K 120 Hz ProXDR display, and blazing 100W SUPERVOOC charging.',
      features: JSON.stringify([
        { title: 'Chipset', value: 'Qualcomm Snapdragon 8 Gen 3 (4nm)' },
        { title: 'Display', value: '6.82" 2K 120Hz ProXDR with LTPO 3.0, 4500 nits peak' },
        { title: 'Camera', value: '50MP Sony LYT-808 + 64MP 3x Periscope + 48MP Ultra-Wide Hasselblad' },
        { title: 'Battery', value: '5400 mAh with 100W SUPERVOOC and 50W AIRVOOC wireless' },
        { title: 'Cooling', value: 'Dual Cryo-velocity VC cooling system (9140mm²)' },
        { title: 'Audio', value: 'Dual Stereo Speakers with Dolby Atmos & Spatial Audio' },
      ]),
      variants: {
        create: [
          {
            name: 'Flowy Emerald 256GB',
            colorName: 'Flowy Emerald',
            colorHex: '#35635B',
            storage: '256GB',
            mrp: 69999,
            price: 64999,
            stock: 25,
            imageUrl: '/images/oneplus-12-emerald.png',
            galleryImages: JSON.stringify(['/images/oneplus-12-emerald.png']),
            isDefault: true,
          },
          {
            name: 'Silky Black 256GB',
            colorName: 'Silky Black',
            colorHex: '#1F2022',
            storage: '256GB',
            mrp: 69999,
            price: 64999,
            stock: 30,
            imageUrl: '/images/oneplus-12-black.png',
            galleryImages: JSON.stringify(['/images/oneplus-12-black.png']),
            isDefault: false,
          },
          {
            name: 'Flowy Emerald 512GB',
            colorName: 'Flowy Emerald',
            colorHex: '#35635B',
            storage: '512GB',
            mrp: 74999,
            price: 69999,
            stock: 14,
            imageUrl: '/images/oneplus-12-emerald.png',
            galleryImages: JSON.stringify(['/images/oneplus-12-emerald.png']),
            isDefault: false,
          },
        ],
      },
      emiPlans: {
        create: [
          {
            tenureMonths: 3,
            interestRate: 0.0,
            monthlyEmi: 22999,
            cashbackAmount: 4000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 30000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 1,
          },
          {
            tenureMonths: 6,
            interestRate: 0.0,
            monthlyEmi: 11499,
            cashbackAmount: 4000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 30000,
            expectedMfReturnsRate: 12.0,
            isPopular: true,
            orderIndex: 2,
          },
          {
            tenureMonths: 12,
            interestRate: 0.0,
            monthlyEmi: 5750,
            cashbackAmount: 4000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 35000,
            expectedMfReturnsRate: 12.0,
            isPopular: true,
            orderIndex: 3,
          },
          {
            tenureMonths: 24,
            interestRate: 0.0,
            monthlyEmi: 2875,
            cashbackAmount: 4000,
            isZeroPercent: true,
            badgeText: '0% interest',
            minMfHolding: 45000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 4,
          },
          {
            tenureMonths: 36,
            interestRate: 10.5,
            monthlyEmi: 2192,
            cashbackAmount: 4000,
            isZeroPercent: false,
            badgeText: '10.5% interest',
            minMfHolding: 50000,
            expectedMfReturnsRate: 12.0,
            isPopular: false,
            orderIndex: 5,
          },
        ],
      },
    },
  });

  console.log('Database seeded successfully!');
  console.log(`Created products: ${iphone17.title}, ${samsungS24.title}, ${pixel9.title}, ${oneplus12.title}`);
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
